import type { Product, Category } from "@/types/shop";

export const DUMMY_CATEGORIES: Category[] = [
  { _id: "c1", name: "Dog Food", slug: "dog-food", icon: "dog" },
  { _id: "c2", name: "Cat Food", slug: "cat-food", icon: "cat" },
  { _id: "c3", name: "Pet Toys", slug: "pet-toys", icon: "toy" },
  { _id: "c4", name: "Medicines", slug: "medicines", icon: "pill" },
  { _id: "c5", name: "Grooming", slug: "grooming", icon: "brush" },
  { _id: "c6", name: "Accessories", slug: "accessories", icon: "collar" },
  { _id: "c7", name: "Vaccines", slug: "vaccines", icon: "syringe" },
];

export const DUMMY_PRODUCTS: Product[] = [
  {
    _id: "p1",
    name: "Royal Canin Adult Dog Food 3kg",
    slug: "royal-canin-adult-dog-food-3kg",
    description:
      "Premium nutrition for adult dogs with balanced protein and omega fatty acids.",
    categorySlug: "dog-food",
    breed: "Golden Retriever",
    images: [
      "https://images.unsplash.com/photo-1589924691995-400dc9ecc119?w=600&q=80",
    ],
    price: 1899,
    compareAtPrice: 2299,
    stock: 45,
    rating: 4.8,
    reviewCount: 312,
    isBestSeller: true,
    tags: ["dog", "food", "premium"],
  },
  {
    _id: "p2",
    name: "Whiskas Ocean Fish Cat Food 1.2kg",
    slug: "whiskas-ocean-fish-cat-food",
    description: "Complete and balanced nutrition for adult cats.",
    categorySlug: "cat-food",
    breed: "",
    images: [
      "https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=600&q=80",
    ],
    price: 449,
    compareAtPrice: 549,
    stock: 80,
    rating: 4.6,
    reviewCount: 198,
    isBestSeller: true,
    tags: ["cat", "food"],
  },
  {
    _id: "p3",
    name: "Interactive Rope Tug Toy",
    slug: "interactive-rope-tug-toy",
    description: "Durable cotton rope toy for active play and dental health.",
    categorySlug: "pet-toys",
    breed: "Labrador",
    images: [
      "https://images.unsplash.com/photo-1601758228041-f3b279525f1f?w=600&q=80",
    ],
    price: 299,
    compareAtPrice: 399,
    stock: 120,
    rating: 4.5,
    reviewCount: 87,
    isBestSeller: false,
    tags: ["toy", "dog"],
  },
  {
    _id: "p4",
    name: "Deworming Tablets (Pack of 4)",
    slug: "deworming-tablets-pack",
    description: "Vet-recommended broad spectrum dewormer for dogs and cats.",
    categorySlug: "medicines",
    breed: "",
    images: [
      "https://images.unsplash.com/photo-1584308664894-14d9f170c3b0?w=600&q=80",
    ],
    price: 199,
    compareAtPrice: 249,
    stock: 60,
    rating: 4.7,
    reviewCount: 156,
    isBestSeller: true,
    tags: ["medicine", "health"],
  },
  {
    _id: "p5",
    name: "Pet Grooming Kit Pro",
    slug: "pet-grooming-kit-pro",
    description: "Brush, comb, nail clipper and deshedding tool in one kit.",
    categorySlug: "grooming",
    breed: "Shih Tzu",
    images: [
      "https://images.unsplash.com/photo-1516734212186-a967f81ad0d8?w=600&q=80",
    ],
    price: 899,
    compareAtPrice: 1199,
    stock: 35,
    rating: 4.4,
    reviewCount: 64,
    isBestSeller: false,
    tags: ["grooming"],
  },
  {
    _id: "p6",
    name: "Reflective Dog Harness & Leash Set",
    slug: "reflective-dog-harness-leash",
    description: "Adjustable padded harness with 1.5m reflective leash.",
    categorySlug: "accessories",
    breed: "German Shepherd",
    images: [
      "https://images.unsplash.com/photo-1605568427561-40dd23c2acea?w=600&q=80",
    ],
    price: 749,
    compareAtPrice: 999,
    stock: 50,
    rating: 4.6,
    reviewCount: 112,
    isBestSeller: true,
    tags: ["accessories", "walk"],
  },
  {
    _id: "p7",
    name: "Anti-Rabies Vaccine (Vet Administered)",
    slug: "anti-rabies-vaccine-vet",
    description: "Schedule at Vet Buddy clinic. Includes consultation.",
    categorySlug: "vaccines",
    breed: "",
    images: [
      "https://images.unsplash.com/photo-1576201836106-db1758fd1c76?w=600&q=80",
    ],
    price: 599,
    compareAtPrice: 699,
    stock: 100,
    rating: 4.9,
    reviewCount: 240,
    isBestSeller: true,
    tags: ["vaccine", "clinic"],
  },
  {
    _id: "p8",
    name: "Husky Breed Puppy Food 2kg",
    slug: "husky-breed-puppy-food-2kg",
    description: "High-energy formula for active northern breeds.",
    categorySlug: "dog-food",
    breed: "Husky",
    images: [
      "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=600&q=80",
    ],
    price: 1299,
    compareAtPrice: 1599,
    stock: 28,
    rating: 4.7,
    reviewCount: 45,
    isBestSeller: false,
    tags: ["dog", "puppy", "husky"],
  },
  {
    _id: "p9",
    name: "Beagle Chew Bone (Pack of 6)",
    slug: "beagle-chew-bone-pack",
    description: "Natural dental chews for medium breeds.",
    categorySlug: "pet-toys",
    breed: "Beagle",
    images: [
      "https://images.unsplash.com/photo-1530281700549-e82e7eb16044?w=600&q=80",
    ],
    price: 399,
    compareAtPrice: 499,
    stock: 70,
    rating: 4.3,
    reviewCount: 33,
    isBestSeller: false,
    tags: ["treat", "chew"],
  },
  {
    _id: "p10",
    name: "Rottweiler Joint Support Supplement",
    slug: "rottweiler-joint-support",
    description: "Glucosamine and chondroitin for large breed joint care.",
    categorySlug: "medicines",
    breed: "Rottweiler",
    images: [
      "https://images.unsplash.com/photo-1450778869185-41d0601e46f5?w=600&q=80",
    ],
    price: 1099,
    compareAtPrice: 1399,
    stock: 22,
    rating: 4.8,
    reviewCount: 78,
    isBestSeller: true,
    tags: ["supplement", "joint"],
  },
  {
    _id: "p11",
    name: "Cat Scratching Post Tower",
    slug: "cat-scratching-post-tower",
    description: "Multi-level sisal post with perch and toy ball.",
    categorySlug: "pet-toys",
    breed: "",
    images: [
      "https://images.unsplash.com/photo-1495360010541-f48722b34f73?w=600&q=80",
    ],
    price: 1599,
    compareAtPrice: 1999,
    stock: 18,
    rating: 4.5,
    reviewCount: 91,
    isBestSeller: false,
    tags: ["cat", "furniture"],
  },
  {
    _id: "p12",
    name: "Flea & Tick Spray 200ml",
    slug: "flea-tick-spray-200ml",
    description: "Fast-acting spray safe for dogs and cats over 8 weeks.",
    categorySlug: "medicines",
    breed: "",
    images: [
      "https://images.unsplash.com/photo-1628009368231-7bb7cfcb0def?w=600&q=80",
    ],
    price: 349,
    compareAtPrice: 429,
    stock: 55,
    rating: 4.4,
    reviewCount: 67,
    isBestSeller: false,
    tags: ["flea", "tick"],
  },
];
